src/App.jsx, src/main.jsx
=> #8 Fix : Import Error 해결

src/components/LayoutKeyword.jsx, src/components/LayoutStock.jsx, src/components/Sidebar.jsx, src/components/SidebarKeyword.jsx, src/components/SidebarStock.jsx, src/pages/ChartPage/ChartPage.jsx, src/pages/KeywordChartPage/KeywordChartPage.jsx, src/pages/LandingPage/LandingPage.jsx, src/pages/StockChartPage/StockChartPage.jsx, src/routers/main-router.jsx
- 채팅 페이지를 제외한 프론트엔드 구조 정리
- sidebar 추가 및 layout 분리, 라우터 수정
=> #11 feat 구조 세팅

package.json, src/App.jsx, src/components/CandleChart.jsx, src/components/CandleChartSimple.jsx, src/components/Chart.jsx, src/components/ChartBox/CandleChart.jsx, src/components/ChartBox/ChartBox.jsx, src/components/ChartBox/ChartData.jsx, src/components/Layout.jsx, src/components/SidebarStock.jsx, src/pages/StockChartPage/StockChartPage.jsx, src/routers/main-router.jsx, src/services/keywordApi.jsx, src/services/userApi.jsx, tailwind.config.js
- 좋아요 버튼 추가
- sidebar 추가
- css 추가
=> #14/feat:stock-ranking-page

src/components/ChartBox/CandleChart.jsx, src/components/ChartBox/ChartBox.jsx, src/components/Layout.jsx, src/components/SidebarStock.jsx
- sidebar css fix
- 페이지 별 sidebar icon hide 처리
=> 14 feat stock ranking page

src/components/SidebarKeyword.jsx, src/pages/KeywordChartPage/KeywordChartPage.jsx, src/routers/main-router.jsx, src/services/keywordApi.jsx
=> Feat#19 키워드 별 종목 랭킹 사이드바

src/components/SidebarKeyword.jsx, src/pages/KeywordChartPage/KeywordChartPage.jsx, src/services/keywordApi.jsx, src/services/userApi.jsx
- 키워드 페이지 즐겨찾기
- 키워드에서 가장 크게 관련된 차트 조회
- 검색어 입력시 추천 검색어 결과 조회
=> #19 Feat : 키워드 페이지 즐겨찾기 및 차트 조회

src/components/ChartBox/UserLike.jsx, src/pages/KeywordChartPage/KeywordChartPage.jsx
=> #29 Fix : 키워드 즐겨찾기 수정

src/components/ChartBox/ChartBox.jsx, src/components/ChartBox/UserLike.jsx, src/components/Layout.jsx, src/pages/LoginPage/LoginPage.jsx, src/pages/SignUpPage/SignUpPage.jsx, src/pages/StockChartPage/StockChartPage.jsx, src/services/stockApi.jsx
- login css
- sign up css
- layout 일부 수정
- api 경로 겹침 수정 및 비동기식 처리 수정
=> #32 feat stock ranking page

src/pages/StockChartPage/StockChartPage.jsx
- search stock css
- search stock 기능 구현
=> feat(#35): search CSS 및 기능 구현

src/components/CandleChartSimple.jsx, src/components/ChartBox/ChartBox.jsx, src/components/ChartBox/ChartData.jsx, src/pages/StockChartPage/StockChartPage.jsx, src/routers/main-router.jsx, src/services/stockApi.jsx
- 주봉, 월봉 추가
- 천의 자리 콤마 및 소수 둘째자리까지 표시
=> [Feat] 주봉 월봉 추가 및 숫자 변환

.env, .github/workflows/deploy.yml, Dockerfile, src/services/chatApi.jsx, src/services/keywordApi.jsx, src/services/stockApi.jsx, src/services/userApi.jsx
=> Refactor#39

src/components/CandleChartSimple.jsx, src/components/ChartBox/ChartBox.jsx
=> #10 [Feat] 월봉 차트 Elder Ray 삭제

src/components/ChartBox/ChartData.jsx
- bullPower, bearPower 값 없을 시에 차트데이터에서 해당 항목 삭제
=> #10 [Feat] bullPower, bearPower 필터링

src/components/ChartBox/CandleChart.jsx
=> #10 [Feat] ema null값 처리

src/pages/KeywordChartPage/KeywordChartPage.jsx
Refactor : 키워드 페이지 차트 추가
- 컴포넌트화 하며 변경될 예정
=> #31 Refactor : 키워드 페이지 차트 추가

src/components/ChartBox/KeywordChartBox.jsx, src/components/ChartBox/UserKeywordLike.jsx, src/components/SearchKeywordInput.jsx, src/pages/KeywordChartPage/KeywordChartPage.jsx, src/utils/keywordFunction.jsx, src/utils/likeFunction.jsx
- 키워드 페이지 CSS 조정
- 키워드용 차트박스 추가
- 키워드용 함수 추가
=> #50 Refactor : 키워드 페이지 CSS 조정

src/components/ChartBox/UserKeywordLike.jsx, src/pages/KeywordChartPage/KeywordChartPage.jsx
=> #50 Refactor : 키워드 차트 페이지 CSS 수정

src/components/SearchKeywordInput.jsx, src/pages/LandingPage/KeywordBox.jsx, src/pages/LandingPage/LandingPage.jsx, src/services/keywordApi.jsx, src/utils/keywordFunction.jsx
=> #61 Feat : 키워드 랜딩 페이지

src/components/SidebarStock.jsx, src/services/keywordApi.jsx
- api 연결 추가
- sidestockbar에서 api 호출 수정
=> feat(#70): keywordApi에 즐겨찾기 랭킹 api 추가 및 sidestockbar에서 api 호출

src/components/SidebarKeyword.jsx, src/services/stockApi.jsx
랜딩 페이지 사이드바 (종목)
- 사용자가 가장 많이 즐겨찾기 한 종목 TOP 10 조회하는 사이드바
- 랜딩 페이지 사이드바 (키워드)와 CSS 맞춤
=> #69 Feat : 랜딩 페이지 사이드바 (종목)

src/components/SearchKeywordInput.jsx, src/pages/KeywordChartPage/KeywordChartPage.jsx
=> #74 Refcator : 키워드 페이지 CSS 수정

src/components/Alarm/Alarm.css, src/components/Alarm/Alarm.jsx, src/components/Header.jsx, src/services/userApi.jsx
=> #72 [Feat] 알림 모달 제작

src/components/Alarm/Alarm.css, src/components/Alarm/Alarm.jsx
- 알림 모달 css 수정
- 스위치 on일 때 슬랙 아이디 빈 경우, 키워드와 종목 모두 선택 안 되었을 경우 경고창 추가
=> #72 [Feat] 알림 모달 css 및 경고창 추가

src/components/Alarm/Alarm.jsx
=> #72 [Feat] 문장 끝 부호 통일

src/pages/ChattingPage/ChattingPage.jsx
=> #82 Refactor : 채팅 연결 URL 수정

src/components/Alarm/Alarm.jsx
- 사용자가 입력한 슬랙 계정이 이메일 형식이 아닐 시, 이메일 형식 요청 추가
=> #72 [Feat] 슬랙 계정 이메일 형식 요청 추가

src/pages/LandingPage/KeywordBox.jsx
=> #86 Refactor : 랜딩페이지 종목 클릭 시 페이지 이동

src/components/ChartBox/CandleChart.jsx, src/pages/LandingPage/StockBox.jsx
=> #89 Refactor : 캔들 차트 에러처리 및 랜딩 페이지 기본값 변경

src/components/Alarm/Alarm.jsx
=> #72 [Feat] 슬랙 링크 추가

src/components/ChartBox/CandleChart.jsx
=> #95 Fix : 차트 예외처리

src/components/Header.jsx, src/components/SearchInput.jsx, src/components/SearchKeywordInput.jsx, src/pages/IntroPage.jsx, src/pages/LandingPage/KeywordBox.jsx, src/pages/LandingPage/StockBox.jsx, src/pages/LoginPage/LoginPage.jsx, src/routers/main-router.jsx
- 기존에 landingpage를 '/'->'/home'으로 수정
- introPage의 경로를 '/'로 설정
- 기타 navigate를 알맞게 변경
- introPage의 css 수정 및 구현
=> feat(#105): intropage를 '/'로 라우팅 및 다른 라우트 수정, 페이지 구현

src/pages/LandingPage/StockBox.jsx, src/services/stockApi.jsx, src/utils/stockFunction.jsx
Refactor : 랜딩 페이지 종목 변경
- 가중치 합이 가장 높은 종목을 보여주도록 변경
=> #108 Refactor : 랜딩 페이지 종목 변경

src/components/Alarm/Alarm.jsx, src/components/ChartBox/ChartBox.jsx, src/components/SidebarChat.jsx, src/components/SidebarMain.jsx, src/pages/LandingPage/KeywordBox.jsx, src/pages/LandingPage/StockBox.jsx, tailwind.config.js
Refactor : 랜딩 페이지 차트 상단에 종목명 추가
=> #114 Refactor : 랜딩 페이지 차트 상단에 종목명 추가

src/components/ChartBox/UserLike.jsx, src/pages/KeywordChartPage/KeywordChartPage.jsx, src/pages/LandingPage/KeywordBox.jsx, src/pages/LandingPage/StockBox.jsx
=> #114 Refactor : 문장 구성 및 CSS 수정

src/components/SidebarChat.jsx
- instruction 멘트 수정 '키워드 -> 키워드 커뮤니티'
=> [Feat] instruction 멘트 수정

src/utils/stockFunction.jsx
=> #126 Refactor : 차트 데이터 에러처리 수정

src/components/ChattingInput.jsx, src/utils/stockFunction.jsx, vite.config.js
=> Version 0.5.2

package.json, src/components/ChattingInput.jsx, vite.config.js
=> Version 0.5.3

package.json, src/components/ChattingBox.jsx, src/components/ChattingInput.jsx, src/components/ChattingMain.jsx, src/components/SidebarMain.jsx
=> Version 0.5.5

src/components/Layout.jsx, src/components/SidebarMain.jsx, src/pages/LandingPage/KeywordBox.jsx, src/pages/LandingPage/StockBox.jsx
=> #114 Refactor : CSS 수정

src/components/ChattingMain.jsx
=> #129 Fix: 메인 사이드바 채팅 메시지 시간 수정

index.html
=> #151 Docs : Favicon 및 Title 변경

src/pages/LandingPage/KeywordBox.jsx, src/pages/LandingPage/StockBox.jsx
- 랜딩페이지 키워드 박스, 주식 박스에 상세보기 버튼 추가
=> [Feat] 상세보기 버튼 추가
